<?php

namespace HL\FantasiaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AsignacionMarcaModeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionMarcaModeloRepository extends EntityRepository
{
}
