<?php

namespace HL\FantasiaBundle\Entity;

/**
 * AsignacionMarcaModeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionMarcaModeloRepository extends \Doctrine\ORM\EntityRepository
{
}
