<?php

namespace HL\FantasiaBundle\Entity;

/**
 * VidrioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VidrioRepository extends \Doctrine\ORM\EntityRepository
{
}
