fantasia_homepage:
    path:     /
    defaults: { _controller: FantasiaBundle:Default:index }

_login:
    path:    /login
    defaults: { _controller: FantasiaBundle:Default:login }	

_logout:
    path:    /logout
    defaults: { _controller: FantasiaBundle:Default:logout }	

FantasiaBundle_cliente:
    resource: "@FantasiaBundle/Resources/config/routing/cliente.yml"
    prefix:   /cliente
