fantasia_homepage:
    path:     /
    defaults: { _controller: FantasiaBundle:Default:index }

_login:
    path:    /login
    defaults: { _controller: FantasiaBundle:Default:login }	

_logout:
    path:    /logout
    defaults: { _controller: FantasiaBundle:Default:logout }	

FantasiaBundle_cliente:
    resource: "@FantasiaBundle/Resources/config/routing/cliente.yml"
    prefix:   /cliente

FantasiaBundle_marca:
    resource: "@FantasiaBundle/Resources/config/routing/marca.yml"
    prefix:   /marca

FantasiaBundle_modelo:
    resource: "@FantasiaBundle/Resources/config/routing/modelo.yml"
    prefix:   /modelo	

FantasiaBundle_abertura:
    resource: "@FantasiaBundle/Resources/config/routing/abertura.yml"
    prefix:   /abertura

FantasiaBundle_vidrio:
    resource: "@FantasiaBundle/Resources/config/routing/vidrio.yml"
    prefix:   /vidrio

FantasiaBundle_carpinteria:
    resource: "@FantasiaBundle/Resources/config/routing/carpinteria.yml"
    prefix:   /carpinteria

FantasiaBundle_presupuesto:
    resource: "@FantasiaBundle/Resources/config/routing/presupuesto.yml"
    prefix:   /presupuesto

_dump:
    path:     /dump
    defaults: { _controller: FantasiaBundle:Default:dump }