abertura:
    path:     /
    defaults: { _controller: "FantasiaBundle:AsignacionMarcaModelo:index" }

abertura_show:
    path:     /{id}/show
    defaults: { _controller: "FantasiaBundle:AsignacionMarcaModelo:show" }

abertura_new:
    path:     /new
    defaults: { _controller: "FantasiaBundle:AsignacionMarcaModelo:new" }

abertura_edit:
    path:     /{id}/edit
    defaults: { _controller: "FantasiaBundle:AsignacionMarcaModelo:edit" }

abertura_update:
    path:     /{id}/update
    defaults: { _controller: "FantasiaBundle:AsignacionMarcaModelo:update" }
    requirements: { _method: post|put }

abertura_delete:
    path:     /{id}/delete
    defaults: { _controller: "FantasiaBundle:AsignacionMarcaModelo:delete" }
