modelo:
    path:     /
    defaults: { _controller: "FantasiaBundle:Modelo:index" }

modelo_show:
    path:     /{id}/show
    defaults: { _controller: "FantasiaBundle:Modelo:show" }

modelo_new:
    path:     /new
    defaults: { _controller: "FantasiaBundle:Modelo:new" }

modelo_edit:
    path:     /{id}/edit
    defaults: { _controller: "FantasiaBundle:Modelo:edit" }

modelo_update:
    path:     /{id}/update
    defaults: { _controller: "FantasiaBundle:Modelo:update" }
    requirements: { _method: post|put }

modelo_delete:
    path:     /{id}/delete
    defaults: { _controller: "FantasiaBundle:Modelo:delete" }
