presupuesto:
    path:     /
    defaults: { _controller: "FantasiaBundle:Presupuesto:index" }

presupuesto_show:
    path:     /{id}/show
    defaults: { _controller: "FantasiaBundle:Presupuesto:show" }

presupuesto_new:
    path:     /new
    defaults: { _controller: "FantasiaBundle:Presupuesto:new" }

presupuesto_edit:
    path:     /{id}/edit
    defaults: { _controller: "FantasiaBundle:Presupuesto:edit" }

presupuesto_update:
    path:     /{id}/update
    defaults: { _controller: "FantasiaBundle:Presupuesto:update" }
    requirements: { _method: post|put }

presupuesto_delete:
    path:     /{id}/delete
    defaults: { _controller: "FantasiaBundle:Presupuesto:delete" }

presupuesto_crear:
    path:     /{id}/crear
    defaults: { _controller: "FantasiaBundle:Presupuesto:crear" }

presupuesto_creando:
    path:     /{id}/creando
    defaults: { _controller: "FantasiaBundle:Presupuesto:creando" }
    requirements: { _method: post|put }

presupuesto_mail:
    path: /{id}/mail
    defaults: {_controller: "FantasiaBundle:Presupuesto:mail"}

presupuesto_imprimir:
    path:     /{id}/{listado}.{_format}
    defaults: { _controller: FantasiaBundle:Presupuesto:imprimir, _format: pdf }
    requirements:
        _format: html|pdf
