vidrio:
    path:     /
    defaults: { _controller: "FantasiaBundle:Vidrio:index" }

vidrio_new:
    path:     /new
    defaults: { _controller: "FantasiaBundle:Vidrio:new" }

vidrio_edit:
    path:     /{id}/edit
    defaults: { _controller: "FantasiaBundle:Vidrio:edit" }

vidrio_update:
   path:     /{id}/update
   defaults: { _controller: "FantasiaBundle:Vidrio:update" }
   requirements: { _method: post|put }

vidrio_delete:
    path:     /{id}/delete
    defaults: { _controller: "FantasiaBundle:Vidrio:delete" }

vidrio_imprimir:
    path:     /{listado}.{_format}
    defaults: { _controller: "FantasiaBundle:Vidrio:imprimir", _format: pdf }
    requirements:
        _format: html|pdf