fantasia:
    resource: "@FantasiaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@FantasiaBundle/Controller/"
    type:     annotation	

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"