<?php

namespace Acme\FantasiaBundle\Entity;

/**
 * CarpinteriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarpinteriaRepository extends \Doctrine\ORM\EntityRepository
{
}
