parameters:
#    acme_fantasia.example.class: Acme\FantasiaBundle\Example

services:
#    acme_fantasia.example:
#        class: %acme_fantasia.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
